package sUserManagement.sop_corba;


/**
* sUserManagement/sop_corba/AdmCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
*     13H51' COT
*/

public interface AdmCllbckIntOperations 
{
  void notificar (String nombreCompleto, int id);
} // interface AdmCllbckIntOperations
