package sUserManagement.sop_corba;


/**
* sUserManagement/sop_corba/AdmCllbckInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
*     13H51' COT
*/

public interface AdmCllbckInt extends AdmCllbckIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdmCllbckInt
