package sUserManagement.sop_corba;


/**
* sUserManagement/sop_corba/FapCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
*     13H51' COT
*/

public interface FapCllbckIntOperations 
{
  void informarIngreso (String nombreCompleto, int id);
} // interface FapCllbckIntOperations
