package sUserManagement.sop_corba;

/**
* sUserManagement/sop_corba/GestionPersonalIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
*     13H51' COT
*/

public final class GestionPersonalIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sUserManagement.sop_corba.GestionPersonalInt value = null;

  public GestionPersonalIntHolder ()
  {
  }

  public GestionPersonalIntHolder (sUserManagement.sop_corba.GestionPersonalInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sUserManagement.sop_corba.GestionPersonalIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sUserManagement.sop_corba.GestionPersonalIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sUserManagement.sop_corba.GestionPersonalIntHelper.type ();
  }

}
