package sUserManagement.sop_corba;

/**
* sUserManagement/sop_corba/personalDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
*     13H51' COT
*/

public final class personalDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sUserManagement.sop_corba.personalDTO value = null;

  public personalDTOHolder ()
  {
  }

  public personalDTOHolder (sUserManagement.sop_corba.personalDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sUserManagement.sop_corba.personalDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sUserManagement.sop_corba.personalDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sUserManagement.sop_corba.personalDTOHelper.type ();
  }

}
