package sUserManagement.sop_corba;


/**
* sUserManagement/sop_corba/usuarioDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
*     13H51' COT
*/

public final class usuarioDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String nombreCompleto = null;
  public String facultad = null;
  public String tipo = null;
  public String fechaIngreso = null;
  public String patologia = null;
  public String usuario = null;
  public String clave = null;

  public usuarioDTO ()
  {
  } // ctor

  public usuarioDTO (int _id, String _nombreCompleto, String _facultad, String _tipo, String _fechaIngreso, String _patologia, String _usuario, String _clave)
  {
    id = _id;
    nombreCompleto = _nombreCompleto;
    facultad = _facultad;
    tipo = _tipo;
    fechaIngreso = _fechaIngreso;
    patologia = _patologia;
    usuario = _usuario;
    clave = _clave;
  } // ctor

} // class usuarioDTO
