package sUserTraking.sop_corba;


/**
* sUserTraking/sop_corba/ArrayAsistenciaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
*     13H51' COT
*/

public final class ArrayAsistenciaHolder implements org.omg.CORBA.portable.Streamable
{
  public sUserTraking.sop_corba.AsistenciaDTO value[] = null;

  public ArrayAsistenciaHolder ()
  {
  }

  public ArrayAsistenciaHolder (sUserTraking.sop_corba.AsistenciaDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sUserTraking.sop_corba.ArrayAsistenciaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sUserTraking.sop_corba.ArrayAsistenciaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sUserTraking.sop_corba.ArrayAsistenciaHelper.type ();
  }

}
