package sUserTraking.sop_corba;


/**
* sUserTraking/sop_corba/AsistenciaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
*     13H51' COT
*/

public final class AsistenciaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int idPaciente = (int)0;
  public String fechaAsistencia = null;
  public String observacion = null;

  public AsistenciaDTO ()
  {
  } // ctor

  public AsistenciaDTO (int _idPaciente, String _fechaAsistencia, String _observacion)
  {
    idPaciente = _idPaciente;
    fechaAsistencia = _fechaAsistencia;
    observacion = _observacion;
  } // ctor

} // class AsistenciaDTO
