package sUserTraking.sop_corba;


/**
* sUserTraking/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
* s�bado 5 de marzo de 2022 12H04' COT
*/

public interface GestionNotificacionesOperations 
{
  void enviarNotificacion (sUserTraking.sop_corba.GestionNotificacionesPackage.notificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
