package sUserTraking.sop_corba;


/**
* sUserTraking/sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
* s�bado 5 de marzo de 2022 10H24' COT
*/

public interface GestionPacientesOperations 
{
  void registrarValoracion (sUserTraking.sop_corba.ValoracionDTO objValoracion, org.omg.CORBA.BooleanHolder res);
  boolean consultarValoracion (int id, sUserTraking.sop_corba.ValoracionDTOHolder objValoracion);
  void registrarProgramaFisico (sUserTraking.sop_corba.ProgramaFisicoDTO objProgramaFisico, org.omg.CORBA.BooleanHolder res);
  boolean consultarProgramaFisico (int id, sUserTraking.sop_corba.ProgramaFisicoDTOHolder objProgramaFisico);
  void registrarAsistencia (sUserTraking.sop_corba.AsistenciaDTO objAsistencia, org.omg.CORBA.BooleanHolder res);
  boolean consultarAsistencia (int id, sUserTraking.sop_corba.ArrayAsistenciaHolder lstAsistencia);
  void contarFaltas (int id, org.omg.CORBA.IntHolder numFaltas);
} // interface GestionPacientesOperations
