package sUserTraking.sop_corba;


/**
* sUserTraking/sop_corba/GestionPacientesInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
*     13H51' COT
*/

public interface GestionPacientesInt extends GestionPacientesIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPacientesInt
