package sUserTraking.sop_corba;


/**
* sUserTraking/sop_corba/ProgramaFisicoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
*     13H51' COT
*/

public final class ProgramaFisicoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int idPaciente = (int)0;
  public String fechaInicio = null;
  public sUserTraking.sop_corba.ProgramaDTO listaProgramaSemana[] = null;

  public ProgramaFisicoDTO ()
  {
  } // ctor

  public ProgramaFisicoDTO (int _idPaciente, String _fechaInicio, sUserTraking.sop_corba.ProgramaDTO[] _listaProgramaSemana)
  {
    idPaciente = _idPaciente;
    fechaInicio = _fechaInicio;
    listaProgramaSemana = _listaProgramaSemana;
  } // ctor

} // class ProgramaFisicoDTO
